[package]
name = "cs50_input"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true
include = ["doc"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
